force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Assignnment__c/Job_Assignnment__c.object-meta.xml
<CustomObject>
    <label>Job Assignnment</label>
    <nameField>
        <label>Job Assignnment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Assignnment__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Job Assignments</relationshipLabel>
    <relationshipName>Job_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Assignnment__c/fields/Technician__c.field-meta.xml
<CustomField>
    <fullName>Technician__c</fullName>
    <label>Technician</label>
    <referenceTo>Technician__c</referenceTo>
    <relationshipLabel>Job Assignments</relationshipLabel>
    <relationshipName>Job_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Technician__c/Technician__c.object-meta.xml
<CustomObject>
    <label>Technician</label>
    <nameField>
        <label>Technician Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Technician__c/fields/Is_Available__c.field-meta.xml
<CustomField>
    <fullName>Is_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/JobTriggerHandler.cls
/**
 * @description Handler class for JobTrigger
 * Automatically assigns available technician 
 * when a new Job is created
 * @author Preetam Parmar
 */
public class JobTriggerHandler {
     /**
     * @description Handles after insert trigger event
     * @param newJobs List of newly created Job records
     */
    
    public static void handleAfterInsert(List<Job__c> newJobs) {
        // Step 1 - Find first available Technician
        List<Technician__c> availableTechs = [
            SELECT Id, Name 
            FROM Technician__c 
            WHERE Is_Available__c = true 
            LIMIT 1
        ];
        
        // Step 2 - If no technician found, stop here
        if(availableTechs.isEmpty()) {
            return;
        }
        
        // Step 3 - Get first available technician
        Technician__c tech = availableTechs[0];
        
        // Step 4 - Built  List Of Job Assignments for all new jobs
        List<Job_Assignnment__c> assignments = new List<Job_Assignnment__c>();
        
        for(Job__c job : newJobs) {
            Job_Assignnment__c assignment = new Job_Assignnment__c(
                Job__c = job.Id,
                Technician__c = tech.Id,
                Assigned_Date__c = Date.today()
            );
            assignments.add(assignment);
        }
        
        // Step 5 -  Bulk Insert all assignments at once
        insert assignments;
    }
}